fieldLayouts:
  4ac09c00-111c-45f8-b318-fbdc62a63b10:
    tabs:
      -
        elements:
          -
            fieldUid: 2302b432-e27b-4377-a4ff-fa9822d3aa4d # Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c443abb7-a691-42af-8bf7-43a176b5ae28 # Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 038eb9ba-6364-432d-b7cd-9709f7fe924f # Tel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: contact
name: Contact
