enableVersioning: false
handle: errors
name: Errors
propagationMethod: all
siteSettings:
  5da841b1-ca0d-46ff-8bb1-04d6c889ac54:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
