isPublic: false
name: App
scope:
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'sections.a82e5b64-a1ec-4303-a3f4-56a53ed71bcd:read' # Blog
  - 'entrytypes.67a1ce4b-345c-456a-a074-b260f85c0274:read' # Blog
  - 'sections.4b7b7a3a-8a5a-48cf-b4cd-d6558753d966:read' # Home
  - 'entrytypes.c8141cf8-689a-40b0-9159-3ea2faace57d:read' # Home
  - 'sections.9d03ff81-21ae-4053-89d0-3042a70e9c40:read' # Pages
  - 'entrytypes.d4bc4e24-90b7-4fd5-8026-144624f854f2:read' # Pages
  - 'entrytypes.86f7cf72-1dfc-4d73-88e1-dd936dcd4dc7:read' # Landing Pages
  - 'volumes.48b97265-8699-4399-a4a9-f63748b29a9b:read' # Images
  - 'volumes.4febe1c1-57e8-4eaf-b476-8e2b265a0e23:read' # Documents
  - 'volumes.218e4a7c-9717-4815-9100-92a99bc98205:read' # Video
  - 'globalsets.b7d092cb-9183-40fe-bfde-4796b697d503:read' # Contact
  - 'usergroups.everyone:read'
  - 'formieForms.all:read'
  - 'formieForms.8b1bdaf9-cf7d-4978-94e9-500e8f0a3986:read'
  - 'formieSubmissions.all:read'
  - 'formieSubmissions.8b1bdaf9-cf7d-4978-94e9-500e8f0a3986:read'
  - 'seomatic.all:read'
  - 'formieSubmissions.all:edit'
  - 'formieSubmissions.all:create'
  - 'formieSubmissions.all:save'
  - 'formieSubmissions.all:delete'
  - 'formieSubmissions.8b1bdaf9-cf7d-4978-94e9-500e8f0a3986:edit'
  - 'formieSubmissions.8b1bdaf9-cf7d-4978-94e9-500e8f0a3986:create'
  - 'formieSubmissions.8b1bdaf9-cf7d-4978-94e9-500e8f0a3986:save'
  - 'formieSubmissions.8b1bdaf9-cf7d-4978-94e9-500e8f0a3986:delete'
